language: python
python: 2.7
env:
- PLONE_VERSION=4.3
matrix:
  allow_failures:
  - env: PLONE_VERSION=4.3
  fast_finish: true
before_install:
- sudo apt-get install libcairo2-dev libpango1.0-dev libffi-dev
install:
- sed -ie "s#travis-5.0.x.cfg#travis-$PLONE_VERSION.x.cfg#" travis.cfg
- python bootstrap-buildout.py
- bin/buildout -c travis.cfg annotate
- bin/buildout -c travis.cfg
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- firefox -v
script:
- bin/code-analysis
- bin/test
after_success:
- bin/createcoverage
- pip install coveralls
- coveralls
notifications:
  email:
  - carlo.moura@alliare.com.br
